// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Author = Collections['authors']['schema']['_output']
export declare const authors: Author[]

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]
